apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 32400
          env:
            - name: PLEX_CLAIM
              value: {{ .Values.env.PLEX_CLAIM }}
          resources: {}
