apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
data:
  postgresqlUsername: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresqlPassword: {{ randAlphaNum 16 | b64enc | quote }}